[language-server.silos]
command = "./target/debug/silos"
args = ["lsp"]

[[language]]
name = "go"
language-servers = [ { name = "silos" }, "gopls" ]

[[language]]
name = "rust"
language-servers = [ ]
